### ISSUE TITLE
iconv-lite should be part of dependencies

### ISSUE THREAD

**Issue by andreinitescu** [blikblum/pdfkit-webpack-example#11]
just a little thing, iconv-lite was missing for me so I had to add it myself

![image](https://user-images.githubusercontent.com/743918/103281315-31f90180-49db-11eb-86fc-fc6f629e206a.png)

**Comment by blikblum** [comment]
iconv-lite is an [optional dependency](https://github.com/foliojs/fontkit/blob/417af0c79c5664271a07a783574ec7fac7ebad0c/src/CmapProcessor.js#L8) used only for fonts without cmap.

A font without cmap is not conformant with the specs and are rare these days

**Comment by blikblum** [comment]
BTW iconv-lite is a pretty big package

**Comment by andreinitescu** [comment]
thanks, it makes sense
