### ISSUE TITLE
ERROR in ./node_modules/_fontkit@1.9.0@fontkit/dist/module.mjs

### ISSUE THREAD

**Issue by rx-app** [blikblum/pdfkit-webpack-example#22]
ERROR in ./node_modules/_fontkit@1.9.0@fontkit/dist/module.mjs 7463:26
Module parse failed: Unexpected token (7463:26)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| };
| class $5340de7a86f3ae85$export$2e2bcd8739ae039 {
>     static zeroMarkWidths = 'AFTER_GPOS';
|     static plan(plan, glyphs, features) {
|         // Plan the features we want to apply
 @ ./node_modules/_pdfkit@0.10.0@pdfkit/js/pdfkit.es5.js 5:0-30 3640:15-22 3642:15-22 3644:15-22      
 @ ./src/index.js

-----------------------------------------------------------------------------------------------------------------------------
how can i solve this promble? i dont kown what error  happend

**Comment by blikblum** [comment]
This example is outdated. You should use the configuration from https://github.com/foliojs/pdfkit/tree/master/examples/webpack
